### PR TITLE
readd compat to fix builder

### PR DESCRIPTION
**Pull request by fblackburn1**
Depends-On: https://github.com/wazo-platform/sf-jobs/pull/33

### CODE REVIEW

**Comment by fblackburn1** [comment]
@sduthil @sileht @fredericlepied 
Any idea how we can solve this?
zuul complain about having 2 compat defined
But our builder want absolutely `debian/compat`
And if I try to remove `debhelper-compat` from control, it seems to have some sort of black magic that readd it ...

**Comment by sduthil** [comment]
recheck

**Comment by sduthil** [comment]
recheck

**Comment by fblackburn1** [comment]
recheck

**Comment by fblackburn1** [comment]
Thanks @sduthil for the fix and upstream patch :+1:

**Pull request merged**
